version: '3'
services:
  my-app:
    #image: public.ecr.aws/y1c9u5a7/js-app:latest
    #image: js-app:1.3
    #image: 070322435379.dkr.ecr.us-east-2.amazonaws.com/js-app:1.1
    image : neileverette/js-app:1.4-remote
    ports:
     - 3000:3000
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
     

volumes:
  mongo-data:
    driver: local
